# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug)
  TARGETDIR = bin/Debug
  TARGET = $(TARGETDIR)/docs
  define BUILDCMDS
	@echo Running build commands
	cldoc generate -I include -- --language c --merge docs --output dochtml --static include/asinine/*
  endef
  define CLEANCMDS
  endef
endif

ifeq ($(config),release)
  TARGETDIR = bin/Release
  TARGET = $(TARGETDIR)/docs
  define BUILDCMDS
	@echo Running build commands
	cldoc generate -I include -- --language c --merge docs --output dochtml --static include/asinine/*
  endef
  define CLEANCMDS
  endef
endif

$(TARGET):
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
