# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  asinine_config = debug
  asn1_config = debug
  x509_config = debug
  tests_config = debug
endif
ifeq ($(config),release)
  asinine_config = release
  asn1_config = release
  x509_config = release
  tests_config = release
endif

PROJECTS := asinine asn1 x509 tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

asinine:
ifneq (,$(asinine_config))
	@echo "==== Building asinine ($(asinine_config)) ===="
	@${MAKE} --no-print-directory -C . -f asinine.make config=$(asinine_config)
endif

asn1: asinine
ifneq (,$(asn1_config))
	@echo "==== Building asn1 ($(asn1_config)) ===="
	@${MAKE} --no-print-directory -C . -f asn1.make config=$(asn1_config)
endif

x509: asinine
ifneq (,$(x509_config))
	@echo "==== Building x509 ($(x509_config)) ===="
	@${MAKE} --no-print-directory -C . -f x509.make config=$(x509_config)
endif

tests: asinine
ifneq (,$(tests_config))
	@echo "==== Building tests ($(tests_config)) ===="
	@${MAKE} --no-print-directory -C . -f tests.make config=$(tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f asinine.make clean
	@${MAKE} --no-print-directory -C . -f asn1.make clean
	@${MAKE} --no-print-directory -C . -f x509.make clean
	@${MAKE} --no-print-directory -C . -f tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   asinine"
	@echo "   asn1"
	@echo "   x509"
	@echo "   tests"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"