# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := asinine dump x509 tests

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

asinine: 
	@echo "==== Building asinine ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f asinine.make

dump: asinine
	@echo "==== Building dump ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f dump.make

x509: asinine
	@echo "==== Building x509 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f x509.make

tests: asinine
	@echo "==== Building tests ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tests.make

clean:
	@${MAKE} --no-print-directory -C . -f asinine.make clean
	@${MAKE} --no-print-directory -C . -f dump.make clean
	@${MAKE} --no-print-directory -C . -f x509.make clean
	@${MAKE} --no-print-directory -C . -f tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   asinine"
	@echo "   dump"
	@echo "   x509"
	@echo "   tests"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
